# -*- coding: utf-8 -*-
"""mlops_cla_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqV6qmm3mSzKqmng7upuf3wL-Ma1NBSf
"""

pip install pandas numpy pyarrow

import pandas as pd
import numpy as np

# 1. Load dataset
df = pd.read_csv("student_performance_dataset.csv")

print("Original dataset:")
print(df.shape)
print(df.head())

# 2. Handle missing values

# Numerical columns
numeric_columns = [
    "study_time_hours",
    "attendance_percent",
    "sleep_hours",
    "previous_grade",
    "final_exam_score"
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

# Categorical column
df["parental_education"] = df["parental_education"].fillna("Unknown")

# 3. Convert Yes/No columns to numerical values

yes_no_columns = [
    "internet_access",
    "extracurricular_activities",
    "part_time_job"
]

for col in yes_no_columns:
    df[col] = (
        df[col]
        .str.strip()
        .str.lower()
        .map({
            "yes": 1,
            "no": 0
        })
    )

df["study_attendance_ratio"] = (
    df["study_time_hours"] /
    df["attendance_percent"].replace(0, np.nan)
)

df["study_attendance_ratio"] = (
    df["study_attendance_ratio"].fillna(0)
)

df["performance_change"] = (
    df["final_exam_score"] -
    df["previous_grade"]
)

df["study_efficiency"] = (
    df["final_exam_score"] /
    df["study_time_hours"].replace(0, np.nan)
)

df["study_efficiency"] = (
    df["study_efficiency"].fillna(0)
)

df["event_timestamp"] = pd.date_range(
    start="2025-01-01",
    periods=len(df),
    freq="h"
)

features_df = df[
    [
        "student_id",
        "study_time_hours",
        "attendance_percent",
        "sleep_hours",
        "previous_grade",
        "internet_access",
        "extracurricular_activities",
        "part_time_job",
        "study_attendance_ratio",
        "performance_change",
        "study_efficiency",
        "event_timestamp"
    ]
].copy()
features_df.to_parquet(
    "student_features.parquet",
    index=False
)

target_df = df[
    [
        "student_id",
        "final_exam_score",
        "final_grade"
    ]
].copy()

target_df.to_csv(
    "student_targets.csv",
    index=False
)

print("\nFeature dataset:")
print(features_df.head())

print("\nFeature dataset shape:")
print(features_df.shape)

print("\nFiles created successfully:")
print("student_features.parquet")
print("student_targets.csv")

!pip install feast pyarrow pandas numpy scikit-learn

!feast version

import os

os.makedirs("student-performance-feast/data", exist_ok=True)
os.makedirs("student-performance-feast/feature_store", exist_ok=True)

print("Folders created!")

import shutil
import os

shutil.copy(
    "student_performance_dataset.csv",
    "student-performance-feast/data/student_performance_dataset.csv"
)

shutil.copy(
    "student_features.parquet",
    "student-performance-feast/data/student_features.parquet"
)

shutil.copy(
    "student_targets.csv",
    "student-performance-feast/data/student_targets.csv"
)

print("Files copied successfully!")

!ls -R student-performance-feast

# Commented out IPython magic to ensure Python compatibility.
# %cd student-performance-feast

!feast init feature_store

!pip install feast pyarrow pandas numpy scikit-learn

!feast version

!feast init feature_store

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/student-performance-feast/feature_store/student_features.py
# 
# from feast import Entity, FeatureView, Field, FileSource
# from feast.types import Float32, Int64
# from datetime import timedelta
# 
# 
# # ---------------------------------------------------
# # 1. ENTITY
# # ---------------------------------------------------
# 
# student = Entity(
#     name="student_id",
#     join_keys=["student_id"],
#     description="Unique identifier for each student"
# )
# 
# 
# # ---------------------------------------------------
# # 2. DATA SOURCE
# # ---------------------------------------------------
# 
# student_source = FileSource(
#     path="/content/student-performance-feast/data/student_features.parquet",
#     timestamp_field="event_timestamp"
# )
# 
# 
# # ---------------------------------------------------
# # 3. FEATURE VIEW
# # ---------------------------------------------------
# 
# student_features = FeatureView(
#     name="student_performance_features",
#     entities=[student],
#     ttl=timedelta(days=365),
#     schema=[
#         Field(
#             name="study_time_hours",
#             dtype=Float32
#         ),
#         Field(
#             name="attendance_percent",
#             dtype=Float32
#         ),
#         Field(
#             name="sleep_hours",
#             dtype=Float32
#         ),
#         Field(
#             name="previous_grade",
#             dtype=Float32
#         ),
#         Field(
#             name="internet_access",
#             dtype=Int64
#         ),
#         Field(
#             name="extracurricular_activities",
#             dtype=Int64
#         ),
#         Field(
#             name="part_time_job",
#             dtype=Int64
#         ),
#         Field(
#             name="study_attendance_ratio",
#             dtype=Float32
#         ),
#         Field(
#             name="performance_change",
#             dtype=Float32
#         ),
#         Field(
#             name="study_efficiency",
#             dtype=Float32
#         ),
#     ],
#     source=student_source,
#     online=True,
#     tags={
#         "project": "student-performance",
#         "purpose": "student-performance-prediction"
#     }
# )

!cat /content/student-performance-feast/feature_store/student_features.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/student-performance-feast/feature_store

!feast apply

!find /content/student-performance-feast -maxdepth 3 -type f

import shutil

shutil.copy(
    "/content/student-performance-feast/feature_store/student_features.py",
    "/content/student-performance-feast/feature_store/feature_repo/student_features.py"
)

print("student_features.py copied successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/student-performance-feast/feature_store/feature_repo

!ls

!feast apply

from feast import FeatureStore
import pandas as pd

# Load Feast feature store
store = FeatureStore(
    repo_path="/content/student-performance-feast/feature_store/feature_repo"
)

# Load student feature data
features = pd.read_parquet(
    "/content/student-performance-feast/data/student_features.parquet"
)

# Create entity dataframe for historical retrieval
entity_df = features[
    ["student_id", "event_timestamp"]
].copy()

# Retrieve historical features
historical_features = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "student_performance_features:study_time_hours",
        "student_performance_features:attendance_percent",
        "student_performance_features:sleep_hours",
        "student_performance_features:previous_grade",
        "student_performance_features:internet_access",
        "student_performance_features:extracurricular_activities",
        "student_performance_features:part_time_job",
        "student_performance_features:study_attendance_ratio",
        "student_performance_features:performance_change",
        "student_performance_features:study_efficiency",
    ],
).to_df()

print("Historical feature retrieval successful!")
print("Shape:", historical_features.shape)
print()
print(historical_features.head())

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


historical_features = historical_features.copy()

targets = pd.read_csv(
    "/content/student-performance-feast/data/student_targets.csv"
)


data = historical_features.merge(
    targets[["student_id", "final_exam_score"]],
    on="student_id",
    how="inner"
)

print("Dataset for ML:")
print(data.shape)
print(data.head())


feature_columns = [
    "study_time_hours",
    "attendance_percent",
    "sleep_hours",
    "previous_grade",
    "internet_access",
    "extracurricular_activities",
    "part_time_job",
    "study_attendance_ratio",
    "performance_change",
    "study_efficiency"
]

X = data[feature_columns]
y = data["final_exam_score"]


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training records:", len(X_train))
print("Testing records:", len(X_test))



model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)


predictions = model.predict(X_test)


mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = mse ** 0.5
r2 = r2_score(y_test, predictions)

print("\nModel Results")
print("-------------------------")
print("MAE :", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R2  :", round(r2, 4))

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/student-performance-feast/feature_store/feature_repo

!feast materialize-incremental 2026-01-01

from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/student-performance-feast/feature_store/feature_repo"
)

online_features = store.get_online_features(
    features=[
        "student_performance_features:study_time_hours",
        "student_performance_features:attendance_percent",
        "student_performance_features:sleep_hours",
        "student_performance_features:previous_grade",
        "student_performance_features:internet_access",
        "student_performance_features:extracurricular_activities",
        "student_performance_features:part_time_job",
        "student_performance_features:study_attendance_ratio",
        "student_performance_features:performance_change",
        "student_performance_features:study_efficiency",
    ],
    entity_rows=[
        {"student_id": 1}
    ],
).to_dict()

print("Online feature retrieval successful!")
print(online_features)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/student-performance-feast/feature_store/feature_repo

!feast materialize 2025-01-01T00:00:00 2025-02-12T00:00:00

from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/student-performance-feast/feature_store/feature_repo"
)

online_features = store.get_online_features(
    features=[
        "student_performance_features:study_time_hours",
        "student_performance_features:attendance_percent",
        "student_performance_features:sleep_hours",
        "student_performance_features:previous_grade",
        "student_performance_features:internet_access",
        "student_performance_features:extracurricular_activities",
        "student_performance_features:part_time_job",
        "student_performance_features:study_attendance_ratio",
        "student_performance_features:performance_change",
        "student_performance_features:study_efficiency",
    ],
    entity_rows=[
        {"student_id": 1}
    ],
).to_dict()

print(online_features)

import pandas as pd

online_df = pd.DataFrame(online_features)

feature_columns = [
    "study_time_hours",
    "attendance_percent",
    "sleep_hours",
    "previous_grade",
    "internet_access",
    "extracurricular_activities",
    "part_time_job",
    "study_attendance_ratio",
    "performance_change",
    "study_efficiency"
]

X_online = online_df[feature_columns]

final_prediction = model.predict(X_online)[0]

print("Student ID:", online_df["student_id"].iloc[0])
print("Predicted Final Exam Score:", round(final_prediction, 2))

